### ISSUE TITLE
Allow sigma image as input noise map

### ISSUE THREAD

**Issue by dr-guangtou** [johnnygreco/pymfit#2]
Currently core.py only allows variance image.  Add an option to make it possible to use Sigma map. 

* For most of my galaxies, since I used to use Galfit, I converted variance map into sigma map.
* Add a new option `sigma=False`;  when True, treat `var_fn` as sigma image.

**Comment by johnnygreco** [comment]
Definitely a useful addition. 

Perhaps we should change `var_fn` to `noise_fn`?

Thanks.

**Comment by dr-guangtou** [comment]
I tried to make a minor change, and will submit a pull request later....I want to learn how to do that. 

I assume most of tests done are using variance images, so I will just keep var_fn as is, so you don't need to change all your codes.  

Best,
Song
